[tool.poetry]
name = "audiozerowatermarking-sc"
version = "0.1.0"
description = ""
authors = ["ioComk <rw110407@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^1.26.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
